set(_CATKIN_CURRENT_PACKAGE "usb_cam")
set(usb_cam_MAINTAINER "Russell Toris <rctoris@wpi.edu>")
set(usb_cam_DEPRECATED "")
set(usb_cam_VERSION "0.1.3")
set(usb_cam_BUILD_DEPENDS "image_transport" "roscpp" "std_msgs" "sensor_msgs" "self_test" "ffmpeg" "camera_info_manager")
set(usb_cam_RUN_DEPENDS "image_transport" "roscpp" "std_msgs" "sensor_msgs" "self_test" "ffmpeg" "camera_info_manager")
set(usb_cam_BUILDTOOL_DEPENDS "catkin")